import datetime
from airflow import models
from airflow.providers.google.cloud.operators.dataproc import DataprocCreateBatchOperator
from airflow.utils.dates import days_ago

# Define your project configurations
PROJECT_ID = "your-gcp-project-id"
REGION = "us-central1"  # Must match your subnet's region
SUBNETWORK_URI = f"projects/{PROJECT_ID}/regions/{REGION}/subnetworks/your-dedicated-dataproc-subnet"

# Define the location of your Spark script and output paths
PYSPARK_FILE = "gs://your-code-bucket/scripts/wordcount.py"
PHS_CLUSTER_NAME = f"projects/{PROJECT_ID}/regions/{REGION}/clusters/your-phs-cluster"

# Define default arguments for the DAG
default_args = {
    "owner": "data-engineering",
    "start_date": days_ago(1),
    "depends_on_past": False,
    "retries": 1,
    "retry_delay": datetime.timedelta(minutes=5),
}

with models.DAG(
    dag_id="dataproc_serverless_batch_trigger",
    default_args=default_args,
    schedule_interval="@daily",  # Adjust your schedule here
    catchup=False,
    tags=["dataproc", "serverless", "pyspark"],
) as dag:

    # Dataproc Serverless PySpark Batch configuration
    # Note: A unique batch_id is automatically generated by the operator if not explicitly provided
    trigger_serverless_pyspark_job = DataprocCreateBatchOperator(
        task_id="run_serverless_pyspark_batch",
        project_id=PROJECT_ID,
        region=REGION,
        batch={
            "pyspark_batch": {
                "main_python_file_uri": PYSPARK_FILE,
                # Optional: Pass application arguments if your script needs them
                "args": ["gs://your-data-bucket/input/", "gs://your-data-bucket/output/"],
            },
            "environment_config": {
                "execution_config": {
                    # Explicitly target your custom carved-out subnet
                    "subnetwork_uri": SUBNETWORK_URI,
                },
                "peripherals_config": {
                    # Best Practice: Connect a Persistent History Server to view logs later
                    "spark_history_server_config": {
                        "dataproc_cluster": PHS_CLUSTER_NAME
                    }
                },
            },
            "runtime_config": {
                # Best Practice: Cap max executors to respect your calculated subnet size
                "properties": {
                    "spark.dynamicAllocation.maxExecutors": "25"
                }
            },
        },
    )

    trigger_serverless_pyspark_job